### ISSUE TITLE
请问您这脚本怎么使用啊？

### ISSUE THREAD

**Issue by yaojingzhe** [117503445/media_srt#1]
您好，您这脚本要加哪些命令参数？请问我要怎么把百度api密钥加进去？能不能教一下我，非常感谢！

**Comment by 117503445** [comment]
不好意思,目前项目搁浅了,不能用.

大体思路是 视频提取出音频,然后音频按照句子分割成小音频,再用百度api处理,最后生成字幕.

目前没有找到 理想的 分割成小音频 的方法.

不知道什么时候会重新开工的:)
